const COUNTRIES = {
	Abkhazia: {continent: "Asia", status: "Terrotory", regex: ["ab[hk]+a[sz]ia"], tags: {}},
	"Afghanistan_-2021": {continent: "Asia", status: "old", regex: ["afgh?anistan"], tags: {}},
	Afghanistan_Taliban: {continent: "Asia", status: "country", regex: ["afgh?anistan"], tags: {}},
	Aland_Islands: {continent: "", status: "", regex: [""], tags: {}},
	Albania: {continent: "Europe", status: "country", regex: ["albania"], tags: {}},
	Algeria: {continent: "Africa", status: "country", regex: ["algeria"], tags: {}},
	American_Samoa: {continent: "Oceania", status: "territory", regex: ["americansamoa"], tags: {}},
	Andorra: {continent: "Europe", status: "country", regex: ["andor+a"], tags: {}},
	Angola: {continent: "Africa", status: "country", regex: ["angola"], tags: {}},
	Anguilla: {continent: "Caribbeans", status: "territory", regex: ["angu?il+a"], tags: {}},
	Antarctica: {continent: "Antarctica", status: "territory", regex: ["antarctica"], tags: {}},
	Antigua_and_Barbuda: {continent: "Caribbeans", status: "country", regex: ["antigua", "barbuda", "antigua(and)?barbuda"], tags: {}},
	Argentina: {continent: "South America", status: "country", regex: ["ar[gj]entina"], tags: {}},
	Armenia: {continent: "Asia", status: "country", regex: ["armenia"], tags: {}},
	"Artsakh_Nagorno-Karabakh": {
		continent: "Asia",
		status: "territory",
		regex: ["ar[cst]+a[hk]+", "nagorno", "karaba[hk]+", "nagornokaraba[hk]+", "ar[cst]+a[hk]+nagornokaraba[hk]+"],
		tags: {},
	},
	Aruba: {continent: "Caribbeans", status: "country", regex: ["aruba"], tags: {}},
	Ascension_Island: {continent: "Africa", status: "territory", regex: ["ascen[cs]ion(island)?"], tags: {}},
	Australia: {continent: "Oceania", status: "country", regex: ["australia"], tags: {}},
	Austria: {continent: "Europe", status: "country", regex: ["austria"], tags: {}},
	Azerbaijan: {continent: "Asia", status: "country", regex: ["azei?rba[hji]+an"], tags: {}},
	Bahrain: {continent: "Asia", status: "country", regex: ["ba[hr]{1,2}ain"], tags: {}},
	Bangladesh: {continent: "Asia", status: "country", regex: ["ban?gladesh"], tags: {}},
	Barbados: {continent: "Caribbeans", status: "country", regex: ["barbados"], tags: {}},
	Barotseland: {continent: "Africa", status: "region", regex: ["barotseland"], tags: {}},
	Basque_Country: {continent: "Europe", status: "region", regex: ["basque", "basquecountr?y"], tags: {}},
	Belarus: {continent: "Europe", status: "country", regex: ["belarus+(ia)?"], tags: {}},
	Belgium: {continent: "Europe", status: "country", regex: ["belgium", "belgia"], tags: {}},
	Belize: {continent: "North America", status: "country", regex: ["beli[sz]e"], tags: {}},
	Benin: {continent: "Africa", status: "country", regex: ["benin"], tags: {}},
	Bermuda: {continent: "North America", status: "territory", regex: ["b[ea]rmuda"], tags: {}},
	Bhutan: {continent: "Asia", status: "country", regex: ["bh?utan"], tags: {}},
	Bolivia: {continent: "South America", status: "country", regex: ["bolivia"], tags: {}},
	Bonaire: {continent: "Caribbeans", status: "territory", regex: ["bonaire?"], tags: {}},
	Bosnia_and_Herzegovina: {continent: "Europe", status: "country", regex: ["bosnia", "her[cz]egovina", "bosnia(and)?her[cz]egovina"], tags: {}},
	Botswana: {continent: "Arfica", status: "country", regex: ["bo(ts|tc|c)wana"], tags: {}},
	Bougainville: {continent: "Oceania", status: "region", regex: ["b[ou]+n?gain?vil+e?"], tags: {}},
	Brazil: {continent: "South America", status: "country", regex: ["bra[sz]il(ia)?"], tags: {}},
	British_Antarctic_Territory: {
		continent: "Antarctica",
		status: "territory",
		regex: ["britishantarctic(territory|territories)?", "(british)?antarctic(territory|territories)"],
		tags: {},
	},
	British_Indian_Ocean_Territory: {continent: "Asia", status: "territory", regex: ["(british)?indian(ocean)?(territory|territories)"], tags: {}},
	British_Virgin_Islands: {continent: "Caribbeans", status: "territory", regex: ["britishvirgin(islands?)?"], tags: {}},
	Brunei: {continent: "Asia", status: "country", regex: ["brun(ai|ei|i)"], tags: {}},
	Bulgaria: {continent: "Europe", status: "country", regex: ["bulgaria"], tags: {}},
	Burkina_Faso: {continent: "Africa", status: "country", regex: ["burkinafaso"], tags: {}},
	Burundi: {continent: "Africa", status: "country", regex: ["burundi"], tags: {}},
	Cambodia: {continent: "Asia", status: "country", regex: ["cambodia"], tags: {}},
	Cameroon: {continent: "Africa", status: "country", regex: ["cameroon"], tags: {}},
	Canada: {continent: "North America", status: "country", regex: ["canada"], tags: {}},
	Cape_Verde: {continent: "Africa", status: "country", regex: ["capeverde", "ca[bp]overde"], tags: {}},
	Catalonia: {continent: "Europe", status: "region", regex: ["catalonia"], tags: {}},
	Cayman_Islands: {continent: "Caribbean", status: "territory", regex: ["cayman", "caymanislands?"], tags: {}},
	Central_African_Republic: {continent: "Africa", status: "country", regex: ["centralafricanrepublic", "car"], tags: {}},
	Chad: {continent: "Africa", status: "country", regex: ["chad"], tags: {}},
	Chechnya: {continent: "Asia", status: "region", regex: ["chechn[iy]a"], tags: {}},
	Chile: {continent: "South America", status: "country", regex: ["chile"], tags: {}},
	China: {continent: "Asia", status: "country", regex: ["china"], tags: {}},
	Christmas_Island: {continent: "Asia", status: "territory", regex: ["christmas(island)?"], tags: {}},
	Cocos_Islands: {continent: "Asia", status: "territory", regex: ["cocos(islands?)?", "keeling(islands?)?", "cocoskeeling(islands?)?"], tags: {}},
	Colombia: {continent: "South America", status: "country", regex: ["col[ou]mbia"], tags: {}},
	Comoros: {continent: "Africa", status: "country", regex: ["comoros"], tags: {}},
	Cook_Islands: {continent: "Oceania", status: "territory", regex: ["cookislands?"], tags: {}},
	Costa_Rica: {continent: "North America", status: "country", regex: ["costarica"], tags: {}},
	Crimea: {continent: "Europe", status: "region", regex: ["crimea"], tags: {}},
	Croatia: {continent: "Europe", status: "country", regex: ["croatia"], tags: {}},
	Cuba: {continent: "Caribbeans", status: "country", regex: ["cuba"], tags: {}},
	Curaçao: {continent: "Caribbeans", status: "country", regex: ["curacao", "curaçao"], tags: {}},
	Cyprus: {continent: "Europe", status: "country", regex: ["cyprus"], tags: {}},
	Czech_Republic_Czechia: {continent: "Europe", status: "country", regex: ["czechrepublic", "czechia"], tags: {}},
	Darfur: {continent: "Africa", status: "region", regex: ["darfur"], tags: {}},
	Democratic_Republic_of_the_Congo: {
		continent: "Africa",
		status: "country",
		regex: ["drc", "democratic(republic|republicof|republicofthe)?congo"],
		tags: {},
	},
	Denmark: {continent: "Europe", status: "country", regex: ["denmark"], tags: {}},
	Djibouti: {continent: "Africa", status: "country", regex: ["djib[uo]{1,2}ti"], tags: {}},
	Dominica: {continent: "Caribbeans", status: "country", regex: ["dominica"], tags: {}},
	Dominican_Republic: {continent: "Caribbeans", status: "country", regex: ["dominicanrepublic"], tags: {}},
	Earth: {continent: "Space", status: "miscellaneous", regex: ["(the)?(planet)?earth"], tags: {}},
	East_Timor: {continent: "Asia", status: "country", regex: ["easttimor", "timorleste"], tags: {}},
	Ecuador: {continent: "South America", status: "country", regex: ["e[cq]uador"], tags: {}},
	Egypt: {continent: "Africa", status: "country", regex: ["egypt"], tags: {}},
	El_Salvador: {continent: "North America", status: "country", regex: ["elsalvador"], tags: {}},
	England: {continent: "Europe", status: "region", regex: ["england"], tags: {partOfACountry: true, partOfUK: true}},
	Equatorial_Guinea: {continent: "Africa", status: "country", regex: ["equatorialguinea"], tags: {}},
	Eritrea: {continent: "Africa", status: "country", regex: ["eritrea"], tags: {}},
	Estonia: {continent: "Europe", status: "country", regex: ["estonia"], tags: {}},
	Eswatini: {continent: "Africa", status: "country", regex: ["eswatini", "swaziland"], tags: {}},
	Ethiopia: {continent: "Arfica", status: "country", regex: ["ethiopia"], tags: {}},
	Falkland_Islands: {continent: "South America", status: "territory", regex: ["falklands", "falklandislands?"], tags: {}},
	Faroe_Islands: {continent: "Europe", status: "territory", regex: ["faroe(islands?)?"], tags: {}},
	Fiji: {continent: "Oceania", status: "country", regex: ["fiji"], tags: {}},
	Finland: {continent: "Europe", status: "country", regex: ["finland"], tags: {}},
	Flemish_Region: {continent: "Europe", status: "region", regex: ["flemish(region)?"], tags: {}},
	France: {continent: "Europe", status: "country", regex: ["france"], tags: {}},
	French_Guiana: {continent: "South America", status: "territory", regex: ["frenchg(ui|uy|y)ana"], tags: {}},
	French_Polynesia: {continent: "Oceania", status: "territory", regex: ["(french)polynesia"], tags: {}},
	French_Southern_and_Antarctic_Lands: {
		continent: "Antarctica",
		status: "territory",
		regex: ["french(southern(and)?)?antarctic(lands?)?"],
		tags: {},
	},
	Gabon: {continent: "Africa", status: "country", regex: ["gabon"], tags: {}},
	Georgia: {continent: "Asia", status: "country", regex: ["georgia"], tags: {}},
	Germany: {continent: "Europe", status: "country", regex: ["germany"], tags: {}},
	Ghana: {continent: "Africa", status: "country", regex: ["ghana"], tags: {}},
	Gibraltar: {continent: "Europe", status: "territory", regex: ["gibraltar"], tags: {}},
	Greece: {continent: "Europe", status: "country", regex: ["gre+ce"], tags: {}},
	Greenland: {continent: "North America", status: "territory", regex: ["greenland"], tags: {}},
	Grenada: {continent: "Caribbeans", status: "country", regex: ["grenada"], tags: {}},
	Guadeloupe: {continent: "Caribbeans", status: "territory", regex: ["guadel[ou]{1,2}pe"], tags: {}},
	Guam: {continent: "North America", status: "territory", regex: ["guam"], tags: {}},
	Guatemala: {continent: "North America", status: "guatemala", regex: [""], tags: {}},
	Guernsey: {continent: "Europe", status: "territory", regex: ["gu?ernsey"], tags: {}},
	Guinea: {continent: "Africa", status: "country", regex: ["guinea"], tags: {}},
	"Guinea-Bissau": {continent: "Africa", status: "country", regex: ["(guinea)?bissau"], tags: {}},
	Guyana: {continent: "South America", status: "country", regex: ["guyana"], tags: {}},
	Haiti: {continent: "Caribbeans", status: "country", regex: ["haiti"], tags: {}},
	Honduras: {continent: "North America", status: "country", regex: ["honduras"], tags: {}},
	Hong_Kong: {continent: "Asia", status: "territory", regex: ["hongkong"], tags: {}},
	Hungary: {continent: "Europe", status: "country", regex: ["hungary"], tags: {}},
	Iceland: {continent: "Europe", status: "country", regex: ["iceland"], tags: {}},
	India: {continent: "Asia", status: "country", regex: ["india"], tags: {}},
	Indonesia: {continent: "Asia", status: "country", regex: ["indonesia"], tags: {}},
	Iran: {continent: "Asia", status: "country", regex: ["iran"], tags: {}},
	Iraq: {continent: "Asia", status: "country", regex: ["iraq"], tags: {}},
	Ireland: {continent: "Europe", status: "country", regex: ["ireland"], tags: {}},
	Isle_of_Man: {continent: "Europe", status: "territory", regex: ["isle(of)?man"], tags: {}},
	Israel: {continent: "Asia", status: "country", regex: ["israel"], tags: {}},
	Italy: {continent: "Europe", status: "country", regex: ["ital(y|ia)"], tags: {}},
	Ivory_Coast: {continent: "Africa", status: "country", regex: ["ivorycoast", "cotedivoire"], tags: {}},
	Jamaica: {continent: "Caribbeans", status: "country", regex: ["jamaica"], tags: {}},
	Japan: {continent: "Asia", status: "country", regex: ["japan"], tags: {}},
	Jersey: {continent: "Europe", status: "territory", regex: ["jersey"], tags: {}},
	Jordan: {continent: "Asia", status: "country", regex: ["jordan"], tags: {}},
	Kazakhstan: {continent: "Asia", status: "country", regex: ["kaza[kh]+stan"], tags: {}},
	Kenya: {continent: "Africa", status: "country", regex: ["kenya"], tags: {}},
	Kiribati: {continent: "Oceania", status: "country", regex: ["kiribati"], tags: {}},
	Kosovo: {continent: "Europe", status: "country", regex: ["kosovo"], tags: {}},
	Kurdistan: {continent: "Asia", status: "region", regex: ["kurdistan"], tags: {}},
	Kuwait: {continent: "Asia", status: "country", regex: ["kuwait"], tags: {}},
	Kyrgyzstan: {continent: "Asia", status: "country", regex: ["kyrgyz?stan"], tags: {}},
	Laos: {continent: "Asia", status: "country", regex: ["laos"], tags: {}},
	Latvia: {continent: "Europe", status: "country", regex: ["latvia"], tags: {}},
	Lebanon: {continent: "Asia", status: "country", regex: ["lebanon"], tags: {}},
	Lesotho: {continent: "Africa", status: "country", regex: ["lesotho"], tags: {}},
	Liberia: {continent: "Africa", status: "country", regex: ["liberia"], tags: {}},
	Libya: {continent: "Africa", status: "country", regex: ["libya"], tags: {}},
	Liechtenstein: {continent: "Europe", status: "country", regex: ["lie?c?htensh?t[aei]i?n"], tags: {}},
	Lithuania: {continent: "Europe", status: "lith?uania", regex: [""], tags: {}},
	Lord_Howe_Island: {continent: "Oceania", status: "territory", regex: ["(lord)?howe?(island)?"], tags: {}},
	Luxembourg: {continent: "Europe", status: "country", regex: ["luxembo?urg"], tags: {}},
	Macau: {continent: "Asia", status: "territory", regex: ["macau"], tags: {}},
	Madagascar: {continent: "Africa", status: "country", regex: ["madagascar"], tags: {}},
	Malawi: {continent: "Africa", status: "country", regex: ["malawi"], tags: {}},
	Malaysia: {continent: "Asia", status: "country", regex: ["malaysia"], tags: {}},
	Maldives: {continent: "Asia", status: "country", regex: ["maldives"], tags: {}},
	Mali: {continent: "Africa", status: "country", regex: ["mali"], tags: {}},
	Malta: {continent: "Europe", status: "country", regex: ["malta"], tags: {}},
	Marshall_Islands: {continent: "Oceania", status: "country", regex: ["marshall(islands?)?"], tags: {}},
	Martinique: {continent: "Caribbeans", status: "territory", regex: ["martinique"], tags: {}},
	Mauritania: {continent: "Africa", status: "country", regex: ["maurith?ania"], tags: {}},
	Mauritius: {continent: "Africa", status: "country", regex: ["mauritius"], tags: {}},
	Mayotte: {continent: "Africa", status: "territory", regex: ["mayot+e"], tags: {}},
	Mexico: {continent: "North America", status: "country", regex: ["mexico"], tags: {}},
	Moldova: {continent: "Europe", status: "country", regex: ["moldova"], tags: {}},
	Monaco: {continent: "Europe", status: "country", regex: ["monaco"], tags: {}},
	Mongolia: {continent: "Asia", status: "country", regex: ["mongolia"], tags: {}},
	Montenegro: {continent: "Europe", status: "country", regex: ["montenegro"], tags: {}},
	Montserrat: {continent: "Caribbeans", status: "territory", regex: ["montser+at"], tags: {}},
	Morocco: {continent: "Africa", status: "country", regex: ["moroc+o"], tags: {}},
	Mozambique: {continent: "Africa", status: "country", regex: ["mozambique"], tags: {}},
	Myanmar: {continent: "Asia", status: "country", regex: ["myanmar", "burma"], tags: {}},
	Namibia: {continent: "Africa", status: "country", regex: ["namibia"], tags: {}},
	Nauru: {continent: "Oceania", status: "country", regex: ["nauru"], tags: {}},
	Nepal: {continent: "Asia", status: "country", regex: ["nepal"], tags: {}},
	Netherlands: {continent: "Europe", status: "country", regex: ["netherlands"], tags: {}},
	New_Caledonia: {continent: "Oceania", status: "territory", regex: ["newcaledonia"], tags: {}},
	New_Zealand: {continent: "Oceania", status: "country", regex: ["newzealand"], tags: {}},
	Nicaragua: {continent: "North America", status: "country", regex: ["nicaragua"], tags: {}},
	Niger: {continent: "Africa", status: "country", regex: ["niger"], tags: {}},
	Nigeria: {continent: "Africa", status: "country", regex: ["nigeria"], tags: {}},
	Niue: {continent: "Oceania", status: "territory", regex: ["niue"], tags: {}},
	Norfolk_Island: {continent: "Oceania", status: "territory", regex: ["norfolk(island)?"], tags: {}},
	North_Korea: {continent: "Asia", status: "country", regex: ["northkorea"], tags: {}},
	North_Macedonia: {continent: "Europe", status: "country", regex: ["northmacedonia"], tags: {}},
	Northern_Cyprus: {continent: "Europe", status: "region", regex: ["northerncyprus"], tags: {}},
	Northern_Ireland: {continent: "Europe", status: "region", regex: ["northernireland"], tags: {}},
	Northern_Mariana_Islands: {continent: "Oceania", status: "territory", regex: ["northernmariana(islands?)?"], tags: {}},
	Norway: {continent: "Europe", status: "country", regex: ["norway"], tags: {}},
	Oman: {continent: "Asia", status: "country", regex: ["oman"], tags: {}},
	Pakistan: {continent: "Asia", status: "country", regex: ["pakistan"], tags: {}},
	Palau: {continent: "Oceania", status: "country", regex: ["palau"], tags: {}},
	Palestine: {continent: "Asia", status: "region", regex: ["palestine"], tags: {}},
	Panama: {continent: "North America", status: "country", regex: ["panama"], tags: {}},
	Papua_New_Guinea: {continent: "Asia", status: "country", regex: ["papuanewguinea"], tags: {}},
	Paraguay: {continent: "South America", status: "country", regex: ["paraguay"], tags: {}},
	Peru: {continent: "South America", status: "country", regex: ["peru"], tags: {}},
	Philippines: {continent: "Asia", status: "country", regex: ["phil+ip+ines"], tags: {}},
	Pitcairn_Islands: {continent: "Oceania", status: "territory", regex: ["pitcairn(islands?)?"], tags: {}},
	Poland: {continent: "Europe", status: "country", regex: ["poland"], tags: {}},
	Portugal: {continent: "Europe", status: "country", regex: ["portugal"], tags: {}},
	Puerto_Rico: {continent: "Caribbeans", status: "territory", regex: ["puertorico"], tags: {}},
	Qatar: {continent: "Asia", status: "country", regex: ["qatar"], tags: {}},
	Quebec: {continent: "North America", status: "region", regex: ["quebec"], tags: {}},
	Republic_of_the_Congo: {continent: "Africa", status: "country", regex: ["republicof(the)?congo", "congo"], tags: {}},
	Reunion: {continent: "Africa", status: "territory", regex: ["reunion"], tags: {}},
	Romania: {continent: "Europe", status: "country", regex: ["romania"], tags: {}},
	Russia: {continent: "Europe", status: "country", regex: ["russia"], tags: {}},
	Rwanda: {continent: "Africa", status: "country", regex: ["rwanda"], tags: {}},
	Saba: {continent: "Caribbeans", status: "territory", regex: ["saba"], tags: {}},
	Saint_Barthelemy: {continent: "Caribbeans", status: "territory", regex: ["saintbarthelemy"], tags: {}},
	Saint_Helena: {continent: "Africa", status: "territory", regex: ["sainthelena"], tags: {}},
	Saint_Kitts_and_Nevis: {continent: "Caribbeans", status: "country", regex: ["saintkitts", "saintkittsandnevis", "saintnevis"], tags: {}},
	Saint_Lucia: {continent: "Caribbeans", status: "country", regex: ["saintlucia"], tags: {}},
	Saint_Pierre_and_Miquelon: {continent: "North America", status: "territory", regex: ["saintpierre", "saint(pierreand)?miquelon"], tags: {}},
	Saint_Vincent_and_the_Grenadines: {
		continent: "Caribbeans",
		status: "country",
		regex: ["saintvincent", "saint(vincentand)?(the)?grenadines"],
		tags: {},
	},
	Samoa: {continent: "Oceania", status: "country", regex: ["samoa"], tags: {}},
	San_Marino: {continent: "Europe", status: "country", regex: ["sanmarino"], tags: {}},
	Sark: {continent: "Europe", status: "territory", regex: ["sark"], tags: {}},
	Saudi_Arabia: {continent: "Asia", status: "country", regex: ["saudiarabia"], tags: {}},
	Scotland: {continent: "Europe", status: "region", regex: ["scotland"], tags: {}},
	Senegal: {continent: "Africa", status: "country", regex: ["senegal"], tags: {}},
	Serbia: {continent: "Europe", status: "country", regex: ["serbia"], tags: {}},
	Seychelles: {continent: "Africa", status: "country", regex: ["seychel+es"], tags: {}},
	Sierra_Leone: {continent: "Africa", status: "country", regex: ["sier+aleone"], tags: {}},
	Singapore: {continent: "Asia", status: "country", regex: ["singapore"], tags: {}},
	Sint_Eustatius: {continent: "Caribbeans", status: "territory", regex: ["sa?inteusta[st]ius"], tags: {}},
	Sint_Maarten: {continent: "Caribbeans", status: "territory", regex: ["sa?intma+rten"], tags: {}},
	Slovakia: {continent: "Europe", status: "country", regex: ["slovakia"], tags: {}},
	Slovenia: {continent: "Europe", status: "country", regex: ["slovenia"], tags: {}},
	Solomon_Islands: {continent: "Oceania", status: "country", regex: ["solomon(islands?)?"], tags: {}},
	Somalia: {continent: "Africa", status: "country", regex: ["somalia"], tags: {}},
	Somaliland: {continent: "Africa", status: "region", regex: ["somaliland"], tags: {}},
	South_Africa: {continent: "Africa", status: "country", regex: ["southafrica"], tags: {}},
	South_Georgia_and_the_South_Sandwich_Islands: {
		continent: "Antarctica",
		status: "territory",
		regex: ["southgeorgia(islands?)?", "(the)?southsandwich(islands?)?", "southgeogriaand(the)?southsandwich(islands?)?"],
		tags: {},
	},
	South_Korea: {continent: "Asia", status: "country", regex: ["southkorea"], tags: {}},
	South_Ossetia: {continent: "Asia", status: "territory", regex: ["southos+etia"], tags: {}},
	South_Sudan: {continent: "Africa", status: "country", regex: ["southsudan"], tags: {}},
	Spain: {continent: "Europe", status: "country", regex: ["spain"], tags: {}},
	Sri_Lanka: {continent: "Asia", status: "country", regex: ["srilanka"], tags: {}},
	Sudan: {continent: "Africa", status: "country", regex: ["sudan"], tags: {}},
	Suriname: {continent: "Africa", status: "country", regex: ["suriname"], tags: {}},
	Sweden: {continent: "Europe", status: "country", regex: ["sweden"], tags: {}},
	Switzerland: {continent: "Europe", status: "country", regex: ["switzerland"], tags: {}},
	Syria: {continent: "Asia", status: "country", regex: ["syria"], tags: {}},
	Sao_Tome_and_Principe: {continent: "Africa", status: "country", regex: ["saotome", "(saotomeand)?principe"], tags: {}},
	Taiwan: {continent: "Asia", status: "country", regex: ["taiwan"], tags: {}},
	Tajikistan: {continent: "Asia", status: "country", regex: ["tajikistan"], tags: {}},
	Tanzania: {continent: "Africa", status: "country", regex: ["tanzania"], tags: {}},
	Thailand: {continent: "Asia", status: "country", regex: ["th?ailand"], tags: {}},
	The_Bahamas: {continent: "Caribbeans", status: "country", regex: ["(the)?bahamas"], tags: {}},
	The_Federated_States_of_Micronesia: {continent: "Oceania", status: "country", regex: ["((the)?federatedstates?of)?micronesia"], tags: {}},
	The_Gambia: {continent: "Africa", status: "country", regex: ["(the)?gambia"], tags: {}},
	Tibet: {continent: "Asia", status: "region", regex: ["tibet"], tags: {}},
	Togo: {continent: "Africa", status: "country", regex: ["togo"], tags: {}},
	Tokelau: {continent: "Oceania", status: "territory", regex: ["tokelau"], tags: {}},
	Tonga: {continent: "Oceania", status: "country", regex: ["tonga"], tags: {}},
	Transnistria: {continent: "Europe", status: "region", regex: ["transnistria"], tags: {}},
	Trinidad_and_Tobago: {continent: "Caribbeans", status: "country", regex: ["trinidad", "tobago", "trinidadandtobago"], tags: {}},
	Tristan_da_Cunha: {continent: "South America", status: "territory", regex: ["tristan", "tristandacunha", "dacunha"], tags: {}},
	Tunisia: {continent: "Africa", status: "country", regex: ["tunisia"], tags: {}},
	Turkmenistan: {continent: "Asia", status: "country", regex: ["turkmenistan"], tags: {}},
	Turks_and_Caicos_Islands: {continent: "Caribbeans", status: "territory", regex: ["turksandcaicos(islands?)?"], tags: {}},
	Tuvalu: {continent: "Oceania", status: "country", regex: ["tuvalu"], tags: {}},
	Turkiye: {continent: "Europe", status: "country", regex: ["turkiye", "turkey"], tags: {}},
	US_Virgin_Islands: {continent: "Caribbeans", status: "territory", regex: ["usvirgin(islands?)?"], tags: {}},
	Uganda: {continent: "Africa", status: "country", regex: ["uganda"], tags: {}},
	Ukraine: {continent: "Europe", status: "country", regex: ["ukraine"], tags: {}},
	United_Arab_Emirates: {continent: "Asia", status: "country", regex: ["uae", "unitedarabemirates"], tags: {}},
	United_Kingdom: {continent: "Europe", status: "country", regex: ["uk", "unitedkingdom"], tags: {}},
	United_States: {continent: "North America", status: "country", regex: ["us", "usa", "unitedstates"], tags: {}},
	Uruguay: {continent: "South America", status: "country", regex: ["uruguay"], tags: {}},
	Uzbekistan: {continent: "Asia", status: "country", regex: ["uzbekistan"], tags: {}},
	Vanuatu: {continent: "Oceania", status: "country", regex: ["vanuatu"], tags: {}},
	Vatican_City: {continent: "Europe", status: "country", regex: ["vatican(city)?", "holysee"], tags: {}},
	Venezuela: {continent: "South America", status: "country", regex: ["venezuela"], tags: {}},
	Vietnam: {continent: "Asia", status: "country", regex: ["vietnam"], tags: {}},
	Wales: {continent: "Europe", status: "region", regex: ["wales"], tags: {}},
	Wallis_and_Futuna: {continent: "Oceaia", status: "territory", regex: ["wallisandfutuna"], tags: {}},
	Wallonia: {continent: "Europe", status: "region", regex: ["wal+onia"], tags: {}},
	West_Papua: {continent: "Asia", status: "region", regex: ["westpapua"], tags: {}},
	Western_Sahara: {continent: "Africa", status: "region", regex: ["westernsahara"], tags: {}},
	Yemen: {continent: "Asia", status: "country", regex: ["yemen"], tags: {}},
	Zambia: {continent: "Africa", status: "country", regex: ["zambia"], tags: {}},
	Zimbabwe: {continent: "Africa", status: "country", regex: ["zimbabwe"], tags: {}},
};
