let ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

const ROTORS = {
	IC: "DMTWSILRUYQNKFEJCAZBPGXOHV",
	IIC: "HQZGPJTMOBLNCIFDYAWVEUSRKX",
	IIIC: "UQNTLSZFMREHDPXKIBVYGJCWOA",
	I: "EKMFLGDQVZNTOWYHXUSPAIBRCJ",
	II: "AJDKSIRUXBLHWTMCQGZNPYFVOE",
	III: "BDFHJLCPRTXVZNYEIWGAKMUSQO",
	IV: "ESOVPZJAYQUIRHXLNFTGKDCMWB",
	V: "VZBRGITYUPSDNHLXAWMJQOFECK",
	VI: "JPGVOUMFYQBENHZRDKASXLICTW",
	VII: "NZJHGRCXMYSWBOUFAIVLPEKQDT",
	VIII: "FKQHTLXOCBJSPDZRAMEWNIUYGV",
	UKW: "QYHOGNECVPUZTFDJAXWMKISRBL",
	ETW: "QWERTZUIOASDFGHJKPYXCVBNML",
	"I-K": "PEZUOHXSCVFMTBGLRINQJWAYDK",
	"II-K": "ZOUESYDKFWPCIQXHMVBLGNJRAT",
	"III-K": "EHRVXGAOBQUSIMZFLYNWKTPDJC",
	"UKW-K": "IMETCGFRAYSQBZXWLHKDVUPOJN",
	"ETW-K": "QWERTZUIOASDFGHJKPYXCVBNML",
	EMPTY: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
	"ABC-BCA": "BCADEFGHIJKLMNOPQRSTUVWXYZ",
};

const REFLECTORS = {
	A: "EJMZALYXVBWFCRQUONTSPIKHGD",
	B: "YRUHQSLDPXNGOKMIEBFZCWVJAT",
	C: "FVPJIAOYEDRZXWGCTKUQSBNMHL",
	EMPTY: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
};
